### ISSUE TITLE
[Bug]: How to solve this error(panic: interface conversion: tg.MessageClass is *tg.MessageEmpty, not *tg.Message)

### ISSUE THREAD

**Issue by kangheeyaa** [tgdrive/teldrive#380]
### Describe the bug

Hello.
I use Teldrive frequently and tend to update to the newest version as soon as it's released 
I've been using the latest version until recently, but when I rebooted the server, I got the following error.
I'd like to know what the problem is and how to solve it.

### Repoduction

I met this issue after rebooting the server.

### Expected behavior

Normal service...

### Version

1.5.4

### Which Platform are you using?

Linux

### Additional context

Here is docker compose logs.

teldrive  | goroutine 122 [running]:
teldrive  | github.com/tgdrive/teldrive/pkg/services.getParts({0x21219f0, 0x4000332d00}, 0x4001061b08, {0x211f018, 0x40002a6060}, 0x4001061688)
teldrive  |     github.com/tgdrive/teldrive/pkg/services/common.go:43 +0x51c
teldrive  | github.com/tgdrive/teldrive/pkg/services.(*FileService).GetFileStream.func1()
teldrive  |     github.com/tgdrive/teldrive/pkg/services/file.go:852 +0x8c
teldrive  | github.com/tgdrive/teldrive/pkg/services.(*FileService).GetFileStream.func2({0x2121750?, 0x4000f3ad20?})
teldrive  |     github.com/tgdrive/teldrive/pkg/services/file.go:874 +0x24
teldrive  | github.com/tgdrive/teldrive/pkg/services.(*FileService).GetFileStream.RunWithAuth.func3({0x2121750, 0x4000f3ad20})
teldrive  |     github.com/tgdrive/teldrive/internal/tgc/run.go:40 +0x36c
teldrive  | github.com/gotd/td/telegram.(*Client).Run.func3({0x2121750, 0x4000f3ad20})
teldrive  |     github.com/gotd/td@v0.111.2/telegram/connect.go:150 +0xa4
teldrive  | github.com/gotd/td/telegram.(*Client).Run.(*CancellableGroup).Go.func6()
teldrive  |     github.com/gotd/td@v0.111.2/tdsync/cancel_group.go:48 +0x30
teldrive  | golang.org/x/sync/errgroup.(*Group).Go.func1()
teldrive  |     golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x54
teldrive  | created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 118
teldrive  |     golang.org/x/sync@v0.8.0/errgroup/errgroup.go:75 +0x98
teldrive  | 2024/11/01 03:32:22 goose: no migrations to run. current version: 20240915121635
teldrive  | 01/11/2024 03:32 AM INFO    Started server http://localhost:8080
teldrive  | panic: interface conversion: tg.MessageClass is *tg.MessageEmpty, not *tg.Message

**Comment by Linden10** [comment]
Ah this is indicative of a ghost file aka you have missing files on telegram side but on the database it appears it's there when it isn't. Something must've happened to cause the file to not upload but be added to your database.

This was resolved with the latest teldrive versions sometime ago, fixing file upload checks and such.

Anyways to resolve this problem, you're going to have to use this script to manually check and remove such ghost files from your database. Instructions on how to use it and requirements to install is on the discord here:
https://discord.com/channels/1142377485737148479/1260921464350179399/1261145708392874064

(Make sure to join the teldrive discord first).

Here's the link to the python script:
https://gist.github.com/danieleg1/1427c2a535b4dd4a6775e0fa82431400

Make sure to read those instructions so you don't accidently delete any files that you deem important! Otherwise you might end on doing something you might regret!

I hope this helps ya out! ^^

**Comment by kangheeyaa** [comment]
Hello.
Thank you for your advice. 
However, I'm not familiar with programming, so I'm not confident about executing the script properly.
For now, I've downgraded to version 1.5.3, and it's working normally....
I will join the Discord and carefully read the information provided there.
Thank you.

**Comment by D0nnieD4rk0** [comment]
had the exact same issue and the script deleted a few files of mine. this project has lost some of its credibility as a cloud storage project but i guess thats what you get for using free* cloud storage.

**Comment by MrR0man** [comment]
> Ah this is indicative of a ghost file aka you have missing files on telegram side but on the database it appears it's there when it isn't. Something must've happened to cause the file to not upload but be added to your database.
> 
> This was resolved with the latest teldrive versions sometime ago, fixing file upload checks and such.
> 
> Anyways to resolve this problem, you're going to have to use this script to manually check and remove such ghost files from your database. Instructions on how to use it and requirements to install is on the discord here: https://discord.com/channels/1142377485737148479/1260921464350179399/1261145708392874064
> 
> (Make sure to join the teldrive discord first).
> 
> Here's the link to the python script: https://gist.github.com/danieleg1/1427c2a535b4dd4a6775e0fa82431400
> 
> Make sure to read those instructions so you don't accidently delete any files that you deem important! Otherwise you might end on doing something you might regret!
> 
> I hope this helps ya out! ^^

dear @Linden10, Could you please provide more details about where the JSON file should be located, or share the instructions here?
The link to the Discord channel is not accessible to me.
Thank you.

**Comment by Fentanest** [comment]
@Linden10 may I ask you some question?
python version = 3.12
I used venv in Ubuntu 24.04
did `pip install hydrogram psycopg2`

when I run

 python3 cleandb.py -f result.json -p -t -d -e

the result is
`
TgCrypto is missing! Hydrogram will work the same, but at a much slower speed. More info: https://docs.hydrogram.org/en/latest/topics/speedups.html
Processing result.json
Loading json...
Done!

Channel: owndrive
Messages: 38

Connecting to database...
Get files from database
Done!
Parts: 348
Total files: 345

Check if telegram files are in db
Files not in db: 34

Traceback (most recent call last):
  File "/home/better0101/json/cleandb.py", line 159, in <module>
    processFile(jsonPath)
  File "/home/better0101/json/cleandb.py", line 82, in processFile
    with tg:
TypeError: 'Client' object does not support the context manager protocol
`

what should I do?
I spent a day to resolve this issue but was not helpful

**Comment by Linden10** [comment]
> > Ah this is indicative of a ghost file aka you have missing files on telegram side but on the database it appears it's there when it isn't. Something must've happened to cause the file to not upload but be added to your database.
> > This was resolved with the latest teldrive versions sometime ago, fixing file upload checks and such.
> > Anyways to resolve this problem, you're going to have to use this script to manually check and remove such ghost files from your database. Instructions on how to use it and requirements to install is on the discord here: https://discord.com/channels/1142377485737148479/1260921464350179399/1261145708392874064
> > (Make sure to join the teldrive discord first).
> > Here's the link to the python script: https://gist.github.com/danieleg1/1427c2a535b4dd4a6775e0fa82431400
> > Make sure to read those instructions so you don't accidently delete any files that you deem important! Otherwise you might end on doing something you might regret!
> > I hope this helps ya out! ^^
> 
> dear @Linden10, Could you please provide more details about where the JSON file should be located, or share the instructions here? The link to the Discord channel is not accessible to me. Thank you.

Ello @MrR0man, allow me to help ya out! So you can't access the discord eh? Well I'll share my guide here for ya.
Make sure to read carefully and follow everything, otherwise you may accidently lose important files or such!
https://gist.github.com/Linden10/71fe9bb4adc13c2de72c73651bfe12d7


> @Linden10 may I ask you some question? python version = 3.12 I used venv in Ubuntu 24.04 did `pip install hydrogram psycopg2`
> 
> ...
> 
> what should I do? I spent a day to resolve this issue but was not helpful

Ello @Fentanest! Let me help ya out!
Hmm...I don't know why this is happening.
Wait your using python 3.12? I never used python 3.12 before so maybe the python script hasn't been updated
to support some new valid code with that?

That or it's something else...
I can only assume trying python 3.11 which is the version I used which the python script worked with for me on Windows.
Hopefully that'll fix it but if not...I'll have to ask the creator of the script on what's wrong.

**Comment by Fentanest** [comment]
> > > Ah this is indicative of a ghost file aka you have missing files on telegram side but on the database it appears it's there when it isn't. Something must've happened to cause the file to not upload but be added to your database.
> > > This was resolved with the latest teldrive versions sometime ago, fixing file upload checks and such.
> > > Anyways to resolve this problem, you're going to have to use this script to manually check and remove such ghost files from your database. Instructions on how to use it and requirements to install is on the discord here: https://discord.com/channels/1142377485737148479/1260921464350179399/1261145708392874064
> > > (Make sure to join the teldrive discord first).
> > > Here's the link to the python script: https://gist.github.com/danieleg1/1427c2a535b4dd4a6775e0fa82431400
> > > Make sure to read those instructions so you don't accidently delete any files that you deem important! Otherwise you might end on doing something you might regret!
> > > I hope this helps ya out! ^^
> > 
> > 
> > dear @Linden10, Could you please provide more details about where the JSON file should be located, or share the instructions here? The link to the Discord channel is not accessible to me. Thank you.
> 
> Ello @MrR0man, allow me to help ya out! So you can't access the discord eh? Well I'll share my guide here for ya. Make sure to read carefully and follow everything, otherwise you may accidently lose important files or such! https://gist.github.com/Linden10/71fe9bb4adc13c2de72c73651bfe12d7
> 
> > @Linden10 may I ask you some question? python version = 3.12 I used venv in Ubuntu 24.04 did `pip install hydrogram psycopg2`
> > ...
> > what should I do? I spent a day to resolve this issue but was not helpful
> 
> Ello @Fentanest! Let me help ya out! Hmm...I don't know why this is happening. Wait your using python 3.12? I never used python 3.12 before so maybe the python script hasn't been updated to support some new valid code with that?
> 
> That or it's something else... I can only assume trying python 3.11 which is the version I used which the python script worked with for me on Windows. Hopefully that'll fix it but if not...I'll have to ask the creator of the script on what's wrong.

@Linden10 Hi, I tried this in Python 3.11, but still got same error....

**Comment by Linden10** [comment]
> > > > Ah this is indicative of a ghost file aka you have missing files on telegram side but on the database it appears it's there when it isn't. Something must've happened to cause the file to not upload but be added to your database.
> > > > This was resolved with the latest teldrive versions sometime ago, fixing file upload checks and such.
> > > > Anyways to resolve this problem, you're going to have to use this script to manually check and remove such ghost files from your database. Instructions on how to use it and requirements to install is on the discord here: https://discord.com/channels/1142377485737148479/1260921464350179399/1261145708392874064
> > > > (Make sure to join the teldrive discord first).
> > > > Here's the link to the python script: https://gist.github.com/danieleg1/1427c2a535b4dd4a6775e0fa82431400
> > > > Make sure to read those instructions so you don't accidently delete any files that you deem important! Otherwise you might end on doing something you might regret!
> > > > I hope this helps ya out! ^^
> > > 
> > > 
> > > dear @Linden10, Could you please provide more details about where the JSON file should be located, or share the instructions here? The link to the Discord channel is not accessible to me. Thank you.
> > 
> > 
> > Ello @MrR0man, allow me to help ya out! So you can't access the discord eh? Well I'll share my guide here for ya. Make sure to read carefully and follow everything, otherwise you may accidently lose important files or such! https://gist.github.com/Linden10/71fe9bb4adc13c2de72c73651bfe12d7
> > > @Linden10 may I ask you some question? python version = 3.12 I used venv in Ubuntu 24.04 did `pip install hydrogram psycopg2`
> > > ...
> > > what should I do? I spent a day to resolve this issue but was not helpful
> > 
> > 
> > Ello @Fentanest! Let me help ya out! Hmm...I don't know why this is happening. Wait your using python 3.12? I never used python 3.12 before so maybe the python script hasn't been updated to support some new valid code with that?
> > That or it's something else... I can only assume trying python 3.11 which is the version I used which the python script worked with for me on Windows. Hopefully that'll fix it but if not...I'll have to ask the creator of the script on what's wrong.
> 
> @Linden10 Hi, I tried this in Python 3.11, but still got same error.... it works without "-e" to just show ghost files. but when I put "-e", it crashed.

Oh really? Strange...hmm....
Say can you try moving cleandb.py out of the json folder and moving it outside of it and than running it with the -f command?
It should look like this:
`python .\cleandb.py -f .\ChatExport_xxxx-xx-xx\result.json -p -t -e`

For python 3.11, it should be:
`py -3.11 .\cleandb.py -f .\ChatExport_xxxx-xx-xx\result.json -p -t -e`

Maybe that'll work? That's how I usually run my python script (on windows, you might need to change the backslashes just in case) and if not, try this next:
`pip uninstall psycopg2 hydrogram`
`pip install -U psycopg2 hydrogram`

This will forcefully upgrade the modules if they're outdated.
For python 3.11, this would be:
`python-3.11 -m pip uninstall psycopg2 hydrogram`
`python-3.11 -m pip install -U psycopg2 hydrogram`

If that still doesn't work...
I guess make sure your folder has read/write support?
The script I believe creates a file called client.session so that should exist when running the script (or running the execute script will make it appear).

If all else fails than...I'll ask the script creator about this issue to them and see if they can figure it out!

**Comment by Diass2** [comment]
Hello everyone, I hope you're all doing well! I'm getting this error in the terminal:

panic: interface conversion: tg.MessageClass is *tg.MessageEmpty, not *tg.Message

goroutine 74 [running]:
github.com/tgdrive/teldrive/pkg/services.getParts({0x2b25e08, 0xc000f14ea0}, 0xc000f6f208, {0x2b23c80, 0xc000274000}, 0xc000272800)
I saw that it could be due to ghost files, but all the files are on Telegram. I noticed that when I send a file larger than 2GB, the title changes to something like: MVI_1983.MP4.part.001 and MVI_1983.MP4.part.002 in the Telegram chat, but in the database it stays as MVI_1983.MP4. Could this be the issue?

The error is especially happening with these files.

**Comment by Linden10** [comment]
> Hello everyone, I hope you're all doing well! I'm getting this error in the terminal:
> 
> panic: interface conversion: tg.MessageClass is *tg.MessageEmpty, not *tg.Message
> 
> goroutine 74 [running]: github.com/tgdrive/teldrive/pkg/services.getParts({0x2b25e08, 0xc000f14ea0}, 0xc000f6f208, {0x2b23c80, 0xc000274000}, 0xc000272800) I saw that it could be due to ghost files, but all the files are on Telegram. I noticed that when I send a file larger than 2GB, the title changes to something like: MVI_1983.MP4.part.001 and MVI_1983.MP4.part.002 in the Telegram chat, but in the database it stays as MVI_1983.MP4. Could this be the issue?
> 
> The error is especially happening with these files.

Ah hello, I see you’re encountering the infamous ghost file issue! I’ve posted a gist link above that links to a guide on how to resolve it so check it out!

Now as for the files having part.001 and such, that’s normal and automatically done by teldrive as they upload the files into parts when they reach telegram’s 2GB limit! Yup, you can upload large files thanks to it heh.

Hope this helps!

**Comment by Diass2** [comment]
> > Hello everyone, I hope you're all doing well! I'm getting this error in the terminal:
> > panic: interface conversion: tg.MessageClass is *tg.MessageEmpty, not *tg.Message
> > goroutine 74 [running]: github.com/tgdrive/teldrive/pkg/services.getParts({0x2b25e08, 0xc000f14ea0}, 0xc000f6f208, {0x2b23c80, 0xc000274000}, 0xc000272800) I saw that it could be due to ghost files, but all the files are on Telegram. I noticed that when I send a file larger than 2GB, the title changes to something like: MVI_1983.MP4.part.001 and MVI_1983.MP4.part.002 in the Telegram chat, but in the database it stays as MVI_1983.MP4. Could this be the issue?
> > The error is especially happening with these files.
> 
> Ah hello, I see you’re encountering the infamous ghost file issue! I’ve posted a gist link above that links to a guide on how to resolve it so check it out!
> 
> Now as for the files having part.001 and such, that’s normal and automatically done by teldrive as they upload the files into parts when they reach telegram’s 2GB limit! Yup, you can upload large files thanks to it heh.
> 
> Hope this helps!

Hello!
So... I saw the link you sent, but the files are both on Telegram and in the Teldrive database as well. They have the same name both in the Telegram chat and inside Teldrive, yet I’m still getting this error. Do you know what else it could be?

**Comment by Linden10** [comment]
> > > Hello everyone, I hope you're all doing well! I'm getting this error in the terminal:
> > > panic: interface conversion: tg.MessageClass is *tg.MessageEmpty, not *tg.Message
> > > goroutine 74 [running]: github.com/tgdrive/teldrive/pkg/services.getParts({0x2b25e08, 0xc000f14ea0}, 0xc000f6f208, {0x2b23c80, 0xc000274000}, 0xc000272800) I saw that it could be due to ghost files, but all the files are on Telegram. I noticed that when I send a file larger than 2GB, the title changes to something like: MVI_1983.MP4.part.001 and MVI_1983.MP4.part.002 in the Telegram chat, but in the database it stays as MVI_1983.MP4. Could this be the issue?
> > > The error is especially happening with these files.
> > 
> > 
> > Ah hello, I see you’re encountering the infamous ghost file issue! I’ve posted a gist link above that links to a guide on how to resolve it so check it out!
> > Now as for the files having part.001 and such, that’s normal and automatically done by teldrive as they upload the files into parts when they reach telegram’s 2GB limit! Yup, you can upload large files thanks to it heh.
> > Hope this helps!
> 
> Hello! So... I saw the link you sent, but the files are both on Telegram and in the Teldrive database as well. They have the same name both in the Telegram chat and inside Teldrive, yet I’m still getting this error. Do you know what else it could be?
> 
> I even downloaded the file from the Telegram chat to check if the video was okay, and it played just fine... However, when I try to play or download it through Teldrive, this error appears...

If they're both on teldrive and telegram and yet you're still getting that error, than that means the following...

The file somehow successfully uploaded to telegram, and is on the database but for some reason....the part number, the number that represents the very telegram message itself in the channel, is either referring to telegram message that's not on telegram anywhere or is incomplete.

Depending on when you uploaded these files with a certain older version of teldrive, this error is apparent due to a bug I discovered and reported a while back which was fixed, in that some files were stuck on the "uploads" table which is a table used for tracking uploads and if say an upload is incomplete, it'll be automatically deleted from telegram channel after a certain time period (default is 1 day or when restarting teldrive I believe).

In this case, the upload completed but something caused the file to remain on the uploads table due to the following scenieros:

1. The file was updated/modified, which on an older versions of teldrive, had a huge bug where files updated would remain stuck on the uploads table despite being uploaded to the database, thus teldrive would automatically delete the telegram message with the part number* tied to it. This bug has since been fixed, but if you uploaded the MP4 and somehow updated it with another of the same mp4...than that might be why.

> * The part number is a telegram message number, that represents the message itself in a channel. So for example, if they're 4 messages in the telegram channel and the 4 messages are 3 files named in order from top to bottom "cat.jpg, cat.mp4.001, cat.mp4.002, cat.jpg", than on the database those 3 files would have a part number referring to them as "1" for cat.jpg located in folder, "2 and 3" for cat.mp4 as the file is more than 2gb, and "4" for cat.jpg again but in a different folder.

2. When uploading the file, the file was at times having upload issues and had to retry (usually leads to orphan files, this happened frequently on older versions of teldrive but since has been rather fixed), this probably caused the file that you uploaded to telegram failing to be properly added to the database and thus one of the files relating to the messages on telegram were deleted by teldrive's automatic cleanup routine with the uploads table.

3. If you were uploading files on teldrive normally and had another instance of teldrive running (like a rclone mount) and uploading files through that at the same time (I think they fixed it in the newer versions as I never had the issue again), there's a chance that teldrive messes up adding the correct part number to the file on the database, leading to error.

4. The file uploaded successfully, but the file remained on the uploads table, probably not properly removed due to reasons with the database (this is different from the first and 2nd scenario), thus teldrive automatically deleted the message on telegram.

5. The rclone version you have, be it an older version that hasn't been updated, caused an error where the file was uploaded to telegram but wasn't properly uploaded to the database...and the 2nd scenario above happened to cause the file to be uploaded to telegram and the database but the message referring to it to be removed...

6. ??? Unknown scenario...

Anyways that's all the reasons I can think of that caused the file to give that telegram empty message.
Please understand that seeing the files both on the database and on telegram doesn't mean that teldrive
itself can access the file.

If you need to re-upload the file but only remains on telegram and split, I can help you with that!
Otherwise if you already have the complete file on your computer/phone/etc, than you can do the following...

1. Update teldrive if you haven't, especially if you're using an older version, found [here](https://github.com/tgdrive/teldrive/releases)!
2. Update rclone, if you use rclone, update to the newest one from [tgdrive's rclone git](https://github.com/tgdrive/rclone/releases) here.
3. After confirming you have the original .MP4 on your computer/phone/etc and nothing will lead to you losing your files...delete the MP4 that's causing the error on your teldrive through the web ui, mount, etc.
4. Re-upload the file with the newest version of rclone and teldrive.
5. After upload, confirm if it works and if it does than...
6. If you want, run the cleandb.py script to remove the orphan* mp4 files on telegram and find other mysterious orphan files/ghost files too.
>* Orphan Files are files that are on telegram but not on the database, caused by errors when uploading, incomplete uploads that weren't properly added to the uploads table or haven't been properly removed, etc.

I hope this helps! Now be wary, teldrive versions 1.6.* just came out and is being updated fixing some odd bugs here or there, if you encounter an unknown error than check the teldrive github (the same with rclone) to see if anything's been updated. If nothing looks updated, check if the release itself has been replaced with a newer version (usually confirmed by seeing how long ago the "Assets" have been updated).

Sometimes a bug is found and fixed immediately but not enough to release a new updated version, just replacing the older teldrive release silently. It can be easy to miss haha but you don't have to worry about it unless you're encountering an huge issue.

Sorry for the long text post!
Hope I explained everything in detail!

**Comment by Diass2** [comment]
I deleted all the ghost files, ran all the commands, and yet when I try to open a file, the following error occurs:

panic: interface conversion: tg.MessageClass is *tg.MessageEmpty, not *tg.Message

goroutine 108 [running]:
github.com/tgdrive/teldrive/pkg/services.getParts({0x2ff21f0, 0xc00031ab00}, 0xc001207208, {0x2fef8b0, 0xc0002780f0}, 0xc001206908)
        github.com/tgdrive/teldrive/pkg/services/common.go:43 +0x552
github.com/tgdrive/teldrive/pkg/services.(*FileService).GetFileStream.func1()
        github.com/tgdrive/teldrive/pkg/services/file.go:867 +0xa9
github.com/tgdrive/teldrive/pkg/services.(*FileService).GetFileStream.func2({0x2ff1f80?, 0xc00035c870?})
        github.com/tgdrive/teldrive/pkg/services/file.go:889 +0x13
github.com/tgdrive/teldrive/pkg/services.(*FileService).GetFileStream.RunWithAuth.func3({0x2ff1f80, 0xc00035c870})
        github.com/tgdrive/teldrive/internal/tgc/run.go:40 +0x503
github.com/gotd/td/telegram.(*Client).Run.func3({0x2ff1f80, 0xc00035c870})
        github.com/gotd/td@v0.116.0/telegram/connect.go:173 +0xb7
github.com/gotd/td/telegram.(*Client).Run.(*CancellableGroup).Go.func6()
        github.com/gotd/td@v0.116.0/tdsync/cancel_group.go:48 +0x23
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.10.0/errgroup/errgroup.go:78 +0x50
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 42
        golang.org/x/sync@v0.10.0/errgroup/errgroup.go:75 +0x96
When I reconnect the server about 10 times, the image opens, but when I try to open another image, the same error happens. What should I do?

There are no more ghost files, and no files on Telegram are missing from the Teldrive database.

**Comment by Linden10** [comment]
> I deleted all the ghost files, ran all the commands, and yet when I try to open a file, the following error occurs:
> 
> panic: interface conversion: tg.MessageClass is *tg.MessageEmpty, not *tg.Message
> 
> goroutine 108 [running]: github.com/tgdrive/teldrive/pkg/services.getParts({0x2ff21f0, 0xc00031ab00}, 0xc001207208, {0x2fef8b0, 0xc0002780f0}, 0xc001206908) github.com/tgdrive/teldrive/pkg/services/common.go:43 +0x552 github.com/tgdrive/teldrive/pkg/services.(*FileService).GetFileStream.func1() github.com/tgdrive/teldrive/pkg/services/file.go:867 +0xa9 github.com/tgdrive/teldrive/pkg/services.(*FileService).GetFileStream.func2({0x2ff1f80?, 0xc00035c870?}) github.com/tgdrive/teldrive/pkg/services/file.go:889 +0x13 github.com/tgdrive/teldrive/pkg/services.(*FileService).GetFileStream.RunWithAuth.func3({0x2ff1f80, 0xc00035c870}) github.com/tgdrive/teldrive/internal/tgc/run.go:40 +0x503 github.com/gotd/td/telegram.(*Client).Run.func3({0x2ff1f80, 0xc00035c870}) github.com/gotd/td@v0.116.0/telegram/connect.go:173 +0xb7 github.com/gotd/td/telegram.(*Client).Run.(*CancellableGroup).Go.func6() github.com/gotd/td@v0.116.0/tdsync/cancel_group.go:48 +0x23 golang.org/x/sync/errgroup.(*Group).Go.func1() golang.org/x/sync@v0.10.0/errgroup/errgroup.go:78 +0x50 created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 42 golang.org/x/sync@v0.10.0/errgroup/errgroup.go:75 +0x96 When I reconnect the server about 10 times, the image opens, but when I try to open another image, the same error happens. What should I do?
> 
> There are no more ghost files, and no files on Telegram are missing from the Teldrive database.
> 
> I no longer have the files on my PC. All of them are stored on Telegram, totaling over 600GB.
> 
> I really appreciate the help you're giving me.

Ah nice to know you were able to successfully delete the ghost files from your database!
Still the fact you're getting the same error is strange and even stranger is that the image loads
after the 10th retry and yet happens again on the next image...

Hmm...I'm guessing you're up-to-date with teldrive already...
I'm not sure why it's still happening...

Hmm...
This is gonna be strange but, is your computers time synced up?
There's a chance that the time is slightly off which causes connection errors when connecting to telegrams servers.

It's probably not that but based on what you described, with the image somehow loading up after 10 retires...
This is the only reason I can think of.
