### ISSUE TITLE
[Bug]: Error post upgrade from 1.5.5 to 1.5.6

### ISSUE THREAD

**Issue by doomwithdon** [tgdrive/teldrive#403]
### Describe the bug

Using non docker implementation on Ubuntu 22 arm64. Repaced the 1.5.5 release with 1.5.6 release and restarted the service.
Faced below error. Had to rollback to 1.5.5.

./teldrive run
panic: failed run migrate: ERROR 20241213121739_index.sql: failed to run SQL migration: failed to execute SQL query "DROP INDEX IF EXISTS teldrive.idx_files_name_search;\nCREATE INDEX IF NOT EXISTS idx_files_name_search ON teldrive.files USING pgroonga (lower(regexp_replace(name, '[^[:alnum:]\\\\s]', ' ', 'g'))) WITH (tokenizer='TokenNgram');\nCREATE INDEX IF NOT EXISTS idx_files_name_regex_search ON teldrive.files USING pgroonga (name pgroonga_text_regexp_ops_v2);": ERROR: operator class "pgroonga_text_regexp_ops_v2" does not exist for access method "pgroonga" (SQLSTATE 42704)

goroutine 1 [running]:
github.com/tgdrive/teldrive/internal/database.NewDatabase(0x40001bcfc8)
        github.com/tgdrive/teldrive/internal/database/database.go:63 +0x414
reflect.Value.call({0x1604c60?, 0x1f47f08?, 0x30?}, {0x1a0fa3a, 0x4}, {0x400000c480, 0x1, 0xeec6b59bf108?})
        reflect/value.go:581 +0x97c
reflect.Value.Call({0x1604c60?, 0x1f47f08?, 0x10?}, {0x400000c480?, 0x40000e2801?, 0x40000f1a10?})
        reflect/value.go:365 +0x94
go.uber.org/dig.defaultInvoker({0x1604c60?, 0x1f47f08?, 0x400005abd0?}, {0x400000c480?, 0x1?, 0x2180bd0?})
        go.uber.org/dig@v1.18.0/container.go:257 +0x28
go.uber.org/dig.(*constructorNode).Call(0x400014e900, {0x2180bd0, 0x400015c790})
        go.uber.org/dig@v1.18.0/constructor.go:187 +0x2a0
go.uber.org/dig.paramSingle.Build({{0x0, 0x0}, 0x0, {0x218ca48, 0x19e4dc0}}, {0x2180bd0, 0x400015c790})
        go.uber.org/dig@v1.18.0/param.go:288 +0x298
go.uber.org/dig.paramList.BuildList({{0x218ca48, 0x1716da0}, {0x40002b69a0, 0x7, 0x7}}, {0x2180bd0, 0x400015c790})
        go.uber.org/dig@v1.18.0/param.go:151 +0xa0
go.uber.org/dig.(*constructorNode).Call(0x400014ecc0, {0x2180bd0, 0x400015c790})
        go.uber.org/dig@v1.18.0/constructor.go:155 +0xc8
go.uber.org/dig.paramSingle.Build({{0x0, 0x0}, 0x0, {0x218ca48, 0x19631a0}}, {0x2180bd0, 0x400015c790})
        go.uber.org/dig@v1.18.0/param.go:288 +0x298
go.uber.org/dig.paramList.BuildList({{0x218ca48, 0x16b5fe0}, {0x4000252320, 0x5, 0x5}}, {0x2180bd0, 0x400015c790})
        go.uber.org/dig@v1.18.0/param.go:151 +0xa0
go.uber.org/dig.(*constructorNode).Call(0x400014efc0, {0x2180bd0, 0x400015c790})
        go.uber.org/dig@v1.18.0/constructor.go:155 +0xc8
go.uber.org/dig.paramSingle.Build({{0x0, 0x0}, 0x0, {0x218ca48, 0x19c4a00}}, {0x2180bd0, 0x400015c790})
        go.uber.org/dig@v1.18.0/param.go:288 +0x298
go.uber.org/dig.paramList.BuildList({{0x218ca48, 0x16b60e0}, {0x4000252370, 0x5, 0x5}}, {0x2180bd0, 0x400015c790})
        go.uber.org/dig@v1.18.0/param.go:151 +0xa0
go.uber.org/dig.(*Scope).Invoke(0x400015c790, {0x16b60e0, 0x1f47ef8}, {0x0, 0x0, 0x31e9a40?})
        go.uber.org/dig@v1.18.0/invoke.go:123 +0x20c
go.uber.org/dig.(*Container).Invoke(0x31e9a30?, {0x16b60e0?, 0x1f47ef8?}, {0x0?, 0x400004db40?, 0x0?})
        go.uber.org/dig@v1.18.0/invoke.go:83 +0x2c
go.uber.org/fx.runInvoke({0xeec66ec94aa8?, 0x400012c578?}, {{0x16b60e0, 0x1f47ef8}, {0x400004e8c0, 0x7, 0x8}})
        go.uber.org/fx@v1.23.0/invoke.go:109 +0x138
go.uber.org/fx.(*module).executeInvoke(0x40002c9790, {{0x16b60e0, 0x1f47ef8}, {0x400004e8c0, 0x7, 0x8}})
        go.uber.org/fx@v1.23.0/module.go:322 +0x118
go.uber.org/fx.(*module).executeInvokes(0x40002c9790)
        go.uber.org/fx@v1.23.0/module.go:308 +0xd0
go.uber.org/fx.New({0x4000171a98, 0x9, 0x0?})
        go.uber.org/fx@v1.23.0/app.go:517 +0x7dc
github.com/tgdrive/teldrive/cmd.runApplication(0x40001bcfc8)
        github.com/tgdrive/teldrive/cmd/run.go:139 +0x5b0
github.com/tgdrive/teldrive/cmd.NewRun.func1(0x4000282400?, {0x1a0f99a?, 0x4?, 0x1a0f99e?})
        github.com/tgdrive/teldrive/cmd/run.go:47 +0x20
github.com/spf13/cobra.(*Command).execute(0x40001d3b08, {0x32378e0, 0x0, 0x0})
        github.com/spf13/cobra@v1.8.1/command.go:989 +0x81c
github.com/spf13/cobra.(*Command).ExecuteC(0x40001d3808)
        github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(0x215a480?, {0x215a640?, 0x400024f7c0?})
        github.com/spf13/cobra@v1.8.1/command.go:1034 +0x48
main.main()
        ./main.go:15 +0x9c

### Repoduction

untar 1.5.6 over 1.5.5 and restart service.

### Expected behavior

Teldrive service should run as expected

### Version

1.5.6

### Which Platform are you using?

Linux

**Comment by doomwithdon** [comment]
Same error even after trying 1.6.0
`01/01/2025 04:59 PM     FATAL   database: failed run migrate: ERROR 20241213121739_index.sql: failed to run SQL migration: failed to execute SQL query "DROP INDEX IF EXISTS teldrive.idx_files_name_search;\nCREATE INDEX IF NOT EXISTS idx_files_name_search ON teldrive.files USING pgroonga (lower(regexp_replace(name, '[^[:alnum:]\\\\s]', ' ', 'g'))) WITH (tokenizer='TokenNgram');\nCREATE INDEX IF NOT EXISTS idx_files_name_regex_search ON teldrive.files USING pgroonga (name pgroonga_text_regexp_ops_v2);": ERROR: operator class "pgroonga_text_regexp_ops_v2" does not exist for access method "pgroonga" (SQLSTATE 42704)`

**Comment by pequenomestrex** [comment]
Do you update to the latest version of pgroonga?

**Comment by doomwithdon** [comment]
supabase doesnt give u the option to upgrade extensions. in any case i solved this by creating a new db and restoring a data backup from the previous db. working fine on 1.6.0 now.
